M:\MKPITS\MKPITS_Monish_Madankar_Java_Aug_2021\Java_Programs\IOFiles\MultipleCatchBlock6.java:8: error: exception ArithmeticException has already been caught
       catch(ArithmeticException e){System.out.println("task1 is completed");}
       ^
M:\MKPITS\MKPITS_Monish_Madankar_Java_Aug_2021\Java_Programs\IOFiles\MultipleCatchBlock6.java:9: error: exception ArrayIndexOutOfBoundsException has already been caught
       catch(ArrayIndexOutOfBoundsException e){System.out.println("task 2 completed");}
       ^
2 errors

Tool completed with exit code 1
